server { listen 80; root /usr/share/nginx/html; index construcciones.html; } 
server {
    listen 80;
    root /usr/share/nginx/html;
    index construcciones.html;

    location / {
        try_files $uri $uri/ /construcciones.html;
    }
}
